# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: os=${{ matrix.os }}, py=${{ matrix.python-version }}

    strategy:
      matrix:
        python-version: ["3.11", "3.13"]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # grab all branches and tags
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Set Up Hatch Env
        run: |
          hatch env create test.py${{ matrix.python-version }}
          hatch env run -e test.py${{ matrix.python-version }} list-env
      - name: Run Tests
        run: |
          hatch env run --env test.py${{ matrix.python-version }} run-coverage
      # - name: Upload coverage
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     verbose: true # optional (default = false)
